[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
chack_gc = "6HRuRBbKZJM8wfeHaNJUr896DHCZJTcCvbvt4rniW62j"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/spacemandev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
